definitions:
  app_features.AppFeature:
    properties:
      description:
        type: string
      enabled:
        type: boolean
      name:
        type: string
    type: object
  app_features.AppFeatureList:
    properties:
      pagination:
        properties:
          first:
            properties:
              href:
                type: string
            type: object
          last:
            properties:
              href:
                type: string
            type: object
          next:
            type: object
          previous:
            type: object
          total_pages:
            type: integer
          total_results:
            type: integer
        type: object
      resources:
        items:
          $ref: '#/definitions/app_features.AppFeature'
        type: array
    type: object
  app_features.UpdateAppFeature:
    properties:
      enabled:
        type: boolean
    required:
    - enabled
    type: object
  config.Error:
    properties:
      errors:
        items:
          $ref: '#/definitions/config.Errors'
        type: array
    type: object
  config.Errors:
    properties:
      code:
        type: integer
      detail:
        type: string
      title:
        type: string
    type: object
  domains.CreateDomain:
    properties:
      internal:
        type: boolean
      metadata:
        properties:
          annotations:
            type: object
          labels:
            type: object
        type: object
      name:
        type: string
      relationships:
        properties:
          organization:
            properties:
              data:
                properties:
                  guid:
                    type: string
                type: object
            type: object
          shared_organizations:
            properties:
              data:
                items:
                  properties:
                    guid:
                      type: string
                  type: object
                type: array
            type: object
        type: object
      router_group:
        type: object
    required:
    - name
    type: object
  organizations.Organizations:
    properties:
      created_at:
        type: string
      guid:
        type: string
      links:
        properties:
          default_domain:
            properties:
              href:
                type: string
            type: object
          domains:
            properties:
              href:
                type: string
            type: object
          quota:
            properties:
              href:
                type: string
            type: object
          self:
            properties:
              href:
                type: string
            type: object
        type: object
      metadata:
        properties:
          annotations:
            type: object
          labels:
            type: object
        type: object
      name:
        type: string
      relationships:
        properties:
          quota:
            properties:
              data:
                properties:
                  guid:
                    type: string
                type: object
            type: object
        type: object
      suspended:
        type: boolean
      updated_at:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /apps/{guid}/features:
    get:
      description: This endpoint retrieves the list of features for the specified
        app.
      parameters:
      - description: App Guid
        in: path
        name: guid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app_features.AppFeatureList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/config.Error'
      security:
      - ApiKeyAuth: []
      summary: List app features
      tags:
      - App Features
  /apps/{guid}/features/{name}:
    get:
      parameters:
      - description: App Guid
        in: path
        name: guid
        required: true
        type: string
      - description: App Feature Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app_features.AppFeature'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/config.Error'
      security:
      - ApiKeyAuth: []
      summary: Get an app feature
      tags:
      - App Features
    patch:
      parameters:
      - description: App Guid
        in: path
        name: guid
        required: true
        type: string
      - description: App Name
        in: path
        name: name
        required: true
        type: string
      - description: Update App Feature
        in: body
        name: UpdateAppFeature
        required: true
        schema:
          $ref: '#/definitions/app_features.UpdateAppFeature'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app_features.AppFeature'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/config.Error'
      security:
      - ApiKeyAuth: []
      summary: Update an app feature
      tags:
      - App Features
  /domains:
    post:
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: string
      - description: "false"
        in: path
        name: internal
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.CreateDomain'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/config.Error'
      security:
      - ApiKeyAuth: []
      summary: Create a domain
      tags:
      - Domains
  /isolation_segments/{guid}/organizations:
    get:
      description: Retrieve the organizations entitled to the isolation segment. Return
        only the organizations the user has access to.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/organizations.Organizations'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/config.Error'
      security:
      - ApiKeyAuth: []
      summary: List organizations for isolation segment
      tags:
      - Organizations
  /organizations:
    get:
      description: Retrieve all organizations the user has access to.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/organizations.Organizations'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/config.Error'
      security:
      - ApiKeyAuth: []
      summary: List organizations
      tags:
      - Organizations
    post:
      parameters:
      - description: org name
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/organizations.Organizations'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/config.Error'
      security:
      - ApiKeyAuth: []
      summary: Create an organization
      tags:
      - Organizations
  /organizations/{guid}:
    get:
      description: Retrieve all organizations the user has access to.
      parameters:
      - description: organization Guid
        in: path
        name: guid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/organizations.Organizations'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/config.Error'
      security:
      - ApiKeyAuth: []
      summary: Get an organization
      tags:
      - Organizations
    patch:
      parameters:
      - description: organization Guid
        in: path
        name: guid
        required: true
        type: string
      - description: org name
        in: body
        name: name
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/organizations.Organizations'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/config.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/config.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/config.Error'
      security:
      - ApiKeyAuth: []
      summary: Update an organization
      tags:
      - Organizations
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: cf-Authorization
    type: apiKey
swagger: "2.0"
